name: Run Bot

on:
  workflow_dispatch:  # Permite ejecutar el workflow manualmente
  schedule:
    - cron: '0 * * * *'  # Ejecuta cada hora (opcional)

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run the bot
        run: node index.js
